### ISSUE TITLE
Ранобэ в истории пользователей

### ISSUE THREAD

**Issue by ren3104** [SecondThundeR/shikithon#13]
При получении истории пользователя все ранобэ парсятся в `Manga` модели, а не `Ranobe`.

Пример:
id=320104646 created_at=datetime.datetime(2023, 1, 24, 20, 41, 20, 645000, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800))) description='Изменена оценка c <b>9</b> на <b>10</b>' ***target=Manga***(id=14893, name='Monogatari Series: First Season', russian='Цикл историй: Первый сезон', image=Image(original='/system/mangas/original/14893.jpg?1675141811', preview='/system/mangas/preview/14893.jpg?1675141811', x96='/system/mangas/x96/14893.jpg?1675141811', x48='/system/mangas/x48/14893.jpg?1675141811'), url='/ranobe/z14893-monogatari-series-first-season', ***kind='light_novel***, score=8.94, status='released', volumes=6, chapters=107, aired_on='2006-11-01', released_on='2010-07-28', english=None, japanese=None, synonyms=None, license_name_ru=None, description=None, description_html=None, description_source=None, franchise=None, favoured=None, anons=None, ongoing=None, thread_id=None, topic_id=None, myanimelist_id=None, rates_scores_stats=None, rates_statuses_stats=None, licensors=None, genres=None, publishers=None, user_rate=None)

**Comment by SecondThundeR** [comment]
Вроде бы починил: https://github.com/SecondThundeR/shikithon/commit/d9d7f7bbd9efa05db84e45463a4779836571f1a8

https://github.com/SecondThundeR/shikithon/blob/d9d7f7bbd9efa05db84e45463a4779836571f1a8/shikithon/models/history.py#L7-L17

Забыл добавить модель ранобэ в юнион для таргета(
~~Если не сложно перепроверить, то буду рад~~

p.s. похоже дело не в этом, а в Pydantic, который путается в моделях и берет почему-то именно мангу, буду думать как это пофиксить

**Comment by SecondThundeR** [comment]
Почекал доку Pydantic еще раз и в итоге каким-то чудом починил этот мем с помощью валидаторов:

https://github.com/SecondThundeR/shikithon/blob/ccb53c5f1f3d4016bb6272fbc8f993257ce28dea/shikithon/models/manga.py#L51-L55
https://github.com/SecondThundeR/shikithon/blob/ccb53c5f1f3d4016bb6272fbc8f993257ce28dea/shikithon/models/ranobe.py#L51-L55

---

Пример с ранобе:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/36604233/217966045-eda848d3-9d24-4777-aeb9-07562ed23ae7.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/36604233/217966076-cb0109a6-dfce-40be-a41f-167376849f70.png">

---

Пример с мангой:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/36604233/217966270-7e82665d-ea98-4736-b5fd-b63cdacf0f1f.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/36604233/217966311-4cf777cc-98c1-4b28-982f-b3d88d284465.png">

---

Пример с аниме:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/36604233/217966402-7362c5ce-88da-4ea3-b739-da6712e80b84.png">
<img width="784" alt="image" src="https://user-images.githubusercontent.com/36604233/217966426-008b3317-86a8-45e0-9e7b-226aa43576ad.png">

---

Вроде бы теперь все работает как надо

**Comment by ren3104** [comment]
Я бы изменил валидацию с `kind` на `url`, потому что это поточнее, как по мне.
`url.startswith('/ranobe')`.

**Comment by SecondThundeR** [comment]
Вот кстати я это не сделал по одной причине. Когда я тестил у себя, то у меня возникали такие случаи, что в поле с ссылкой почему-то сама ссылка начиналась с `/mangas` (хотя когда переходишь по ней, тебя кидает на `/ranobe`

<img width="951" alt="image" src="https://user-images.githubusercontent.com/36604233/218007997-d8c09e40-67e2-4a32-8495-96cde6b58afe.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/36604233/218008083-335e0216-2f19-4fc6-ae17-7dd1c015d724.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/36604233/218008096-6a9a3578-fe7c-47bd-b248-9fb17e2dfea2.png">

Так что я подумал, что надежнее будет все же ориентироваться по полю `kind`
<img width="859" alt="image" src="https://user-images.githubusercontent.com/36604233/218008618-669ee91d-cd0e-45e4-9708-a172f728c413.png">

**Comment by SecondThundeR** [comment]
Еще раз потестил остальную работу с новыми валидаторами и пока что отвалилась только модель манги, ибо в нем типов еще больше, поэтому вынес их в отдельную константу
https://github.com/SecondThundeR/shikithon/blob/60665084ff8e911a80d8a6f90574ce1337f77657/shikithon/models/manga.py#L14
В остальном ничего такого не заметил, так что закрываю этот issue и делаю релиз с фиксом
